### ISSUE TITLE
为什么这个项目只需要运行npm run serve后，没有启动后台的对应项目，就可以请求到数据

### ISSUE THREAD

**Issue by f-kaixin** [wangxinleo/learnVue_shop#5]
如题，npm run serve后，在本地8080端口打开该项目。
后台的vueShow_Server服务端项目没有启动，但是像登录，查询用户、商品列表数据之类的请求都能成功且返回正常的数据。

**Comment by wangxinleo** [comment]
因为本项目已经默认了 B站用户：洛天依保护协会 友情提供的长期的 www.liulongbin.top:8888 后台接口，所以你只需要启动前端项目就可以有完整的API服务。 具体可以在浏览器中按F12，进入Network 监听请求包即可知道向哪个服务器请求了数据。感谢你的issue :heart:

**Comment by f-kaixin** [comment]
好的。
不好意思，是我没注意到前端的请求配置baseurl是三方的服务器url，我改了一下可以了。
